In [2]:
#import a library called pandas which has functions to handle database and tables.For internal use, we are storing/naming as pd
import pandas as pd

In [4]:
#Data Collection.Storing the CSV file datas to dataset variable. read_csv is a function to read csv file.This function is stored in pandas library.
dataset=pd.read_csv("Salary_Data.csv")

In [6]:
#checking if the inputs are stored in memory of dataset variable
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [18]:
#Input Output Split. Saving Input data Years of experience to the input variable-Independent
independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [20]:
#Input Output Split. Saving Outut data Salary to the output variable-Dependent
dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [22]:
#Train&Test Set Split. using 30% of the input for test set. input and output datas are split into 4 variables. Input has test & train. Output has test and train.
#Hence 4 variable. model selection is a class in sklearn library. train_test_split is a function inside model_selection class
from sklearn.model_selection import train_test_split

In [24]:
#Moving the test and train data to respective variables
(X_train,X_test,Y_train,Y_test)=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [26]:
X_train

    YearsExperience
22              7.9
5               2.9
16              5.1
8               3.2
14              4.5
23              8.2
20              6.8
1               1.3
29             10.5
6               3.0
4               2.2
18              5.9
19              6.0
9               3.7
7               3.2
25              9.0
3               2.0
0               1.1
21              7.1
15              4.9
12              4.0

In [28]:
X_test

    YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7
27              9.6
11              4.0
17              5.3

In [32]:
Y_train

      Salary
22  101302.0
5    56642.0
16   66029.0
8    64445.0
14   61111.0
23  113812.0
20   91738.0
1    46205.0
29  121872.0
6    60150.0
4    39891.0
18   81363.0
19   93940.0
9    57189.0
7    54445.0
25  105582.0
3    43525.0
0    39343.0
21   98273.0
15   67938.0
12   56957.0

In [34]:
Y_test

      Salary
2    37731.0
28  122391.0
13   57081.0
10   63218.0
26  116969.0
24  109431.0
27  112635.0
11   55794.0
17   83088.0

In [36]:
#Model Creation.importing class Linear Regression from linear_model class inside sklearn library.Creating Linear Regression model.The result of that function is stored in 
#regressor variable.fit function is use to plot the train set in the Linear regression model to find the model equation by calculating the weight and bias
from sklearn.linear_model import LinearRegression

In [38]:
regressor=LinearRegression()

In [40]:
regressor.fit(X_train,Y_train)

LinearRegression()

In [44]:
#w value is stored in coef_variable in the regression function.
weight=regressor.coef_

In [46]:
weight

array([[9360.26128619]])

In [62]:
#b value is stored in intercept_variable in the regression function.
bias=regressor.intercept_

In [64]:
bias

array([26777.3913412])

In [66]:
#running the model using test data input and predicting the output using the linear regression model we created
Y_pred=regressor.predict(X_test)

In [68]:
#Evaluation metrics. using the r2_score function in the metrics class inside the sklearn library.
#If r2 score value in near to 1, it means our mode is working well. if it is close to 0, it is not working well.
from sklearn.metrics import r2_score

In [70]:
r_score=r2_score(Y_test,Y_pred)

In [72]:
r_score

0.9740993407213511

In [74]:
#Save the Model. saving the file under the name mentioned below. wb means write binary.
import pickle
filename="finalized_slr_model_packyapriya.sav"
pickle.dump(regressor,open(filename,'wb'))

In [82]:
#loading the saved model. enter the value inside predict function parameter. run for result.The result shown below is for 15 years of experience
loaded_model=pickle.load(open("finalized_slr_model_packyapriya.sav",'rb'))

In [94]:
result=loaded_model.predict([[15]])
result

C:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[167181.3106341]])